site_name: The MDL Programming Language
repo_url: https://github.com/taradinoc/mdl-docs

theme: readthedocs

markdown_extensions:
  - admonition

nav:
  - Home: "index.md"
  - "Front matter": "00-front-matter.md"
  - "Chapter 1: Basic Introduction": "01-basic-introduction.md"
  - "Chapter 2: Read, Evaluate, and Print": "02-read-evaluate-print.md"
  - "Chapter 3: Built-in Functions": "03-built-in-functions.md"
  - "Chapter 4: Values of Atoms": "04-values-of-atoms.md"
  - "Chapter 5: Simple Functions": "05-simple-functions.md"
  - "Chapter 6: Data Types": "06-data-types.md"
  - "Chapter 7: Structured Objects": "07-structured-objects.md"
  - "Chapter 8: Truth": "08-truth.md"
  - "Chapter 9: Functions": "09-functions.md"
  - "Chapter 10: Looping": "10-looping.md"
  - "Chapter 11: Input/Output": "11-input-output.md"
  - "Chapter 12: Locatives": "12-locatives.md"
  - "Chapter 13: Association (Properties)": "13-association-properties.md"
  - "Chapter 14: Data-type Declarations": "14-data-type-declarations.md"
  - "Chapter 15: Lexical Blocking": "15-lexical-blocking.md"
  - "Chapter 16: Errors, Frames, etc.": "16-errors-frames-etc.md"
  - "Chapter 17: Macro Operations": "17-macro-operations.md"
  - "Chapter 18: Machine Words and Bits": "18-machine-words-and-bits.md"
  - "Chapter 19: Compiled Programs": "19-compiled-programs.md"
  - "Chapter 20: Coroutines": "20-coroutines.md"
  - "Chapter 21: Interrupts": "21-interrupts.md"
  - "Chapter 22: Storage Management": "22-storage-management.md"
  - "Chapter 23: MDL as a System Process": "23-mdl-as-a-system-process.md"
  - "Chapter 24: Efficiency and Tastefulness": "24-efficiency-and-tastefulness.md"
  - "Appendix 1: A Look Inside": "appendix-1-a-look-inside.md"
  - "Appendix 2: Predefined Subroutines": "appendix-2-predefined-subroutines.md"
  - "Appendix 3: Predefined Types": "appendix-3-predefined-types.md"
  - "Appendix 4: Error Messages": "appendix-4-error-messages.md"
  - "Appendix 5: Initial Settings": "appendix-5-initial-settings.md"
  - "References": "appendix-6-references.md"
  - "Topic Index": "appendix-7-topic-index.md"
  - "Official Distribution List": "appendix-9-official-distribution-list.md"
