site_name: The MDL Programming Language
repo_url: https://github.com/itafroma/mdl-docs/

theme: readthedocs

markdown_extensions:
  - admonition

pages:
  - Home: "index.markdown"
  - "Front matter": "0-front-matter.markdown"
  - "Chapter 1: Basic Introduction": "1-basic-introduction.markdown"
  - "Chapter 2: Read, Evaluate, and Print": "2-read-evaluate-print.markdown"
  - "Chapter 3: Built-in Functions": "3-built-in-functions.markdown"
  - "Chapter 4: Values of Atoms": "4-values-of-atoms.markdown"
  - "Chapter 5: Simple Functions": "5-simple-functions.markdown"
  - "Chapter 6: Data Types": "6-data-types.markdown"
  - "Chapter 7: Structured Objects": "7-structured-objects.markdown"
  - "Chapter 8: Truth": "8-truth.markdown"
